name: build arch package
on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        working-directory: builder
        run: docker build . --tag builder:latest

      - name: run docker image
        working-directory: builder
        run: |
          docker run -i \
          -e GITHUB_KEY=${{ secrets.GITHUB_TOKEN }} \
          -e REPO=${{ github.repository }} \
          -e PKG_NAME="tor-browser" \
          builder:latest
